### ISSUE TITLE
支付宝免签那个同时有两个人支付就会出现混乱了

### ISSUE THREAD

**Issue by ccwy** [ChenSee/ss-panel-v3-mod_Uim-alipay-wxpay#1]
两个人或者更多人同时支付相同金额，就会出现混乱了，有些人只是点开试一下，然后别人付款的就会到他账号上了

**Comment by ccwy** [comment]
现有的逻辑判断，只判断了订单号是否存在与数据库，付款时间要求小于当前时间，我加了个限制，就是付款时间和当前时间最大间隔不超过2分钟，还是没法避免出现多个人点开支付了

**Comment by ChenSee** [comment]
有个思路 可以用第三方的生成二维码 加订单号备注。

**Comment by ccwy** [comment]
现在做法是每次只允许创建一个订单，3分钟后才可以创建新订单了

**Comment by ChenSee** [comment]
我在研究xposed hook 看看弄一个生成二维码的xposed软件
