### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by free3nvy** [ChenSee/ss-panel-v3-mod_Uim-alipay-wxpay#10]
cookie无失效，支付完之后二维码保持不动，余额未增加

**Comment by snokin** [comment]
原因很多。八成是定时任务没设置对。进去你的网站目录下的storage/目录下新建一个logs目录，然后进去刷新一下会不会生成一个log文件？没有的话crontab -e里的内容看看设置对了没。

**Comment by free3nvy** [comment]
> 原因很多。八成是定时任务没设置对。进去你的网站目录下的storage/目录下新建一个logs目录，然后进去刷新一下会不会生成一个log文件？没有的话crontab -e里的内容看看设置对了没。

大佬 没用啊，目录和logs文件都弄好了，crontab -e文件也写好了 logs里正常输出的
就是付款了没反应

**Comment by free3nvy** [comment]
支付宝监听暂停中
支付宝监听第n次运行中
log中就是没有订单生成的信息 即使我付款了

**Comment by ChenSee** [comment]
时区对吗？时间必须是国内时间一致

**Comment by free3nvy** [comment]
> 时区对吗？时间必须是国内时间一致

阿里云的服务器，sh命令 date时间是一样的

**Comment by free3nvy** [comment]
> 时区对吗？时间必须是国内时间一致

大佬帮帮忙 监听正常的 扫码也正常的 就是跳不过去 余额没变过

**Comment by ChenSee** [comment]
composer info chen-see/chen-pay
composer update chen-see/chen-pay

截图log

**Comment by free3nvy** [comment]
谢谢大佬，我知道哪里有问题了 已经解决

**Comment by free3nvy** [comment]
> composer info chen-see/chen-pay
> composer update chen-see/chen-pay
> 
> 截图log


![1111111111](https://user-images.githubusercontent.com/20753738/60391554-948dea80-9b23-11e9-875a-73c30d6275bc.jpg)
大佬 手机端点入支付宝以后
“暂不支持此种操作，请在支付宝内打开操作”
这是啥原因呀

**Comment by ChenSee** [comment]
这是因为固定金额付款码的原因，换成输入金额的码就好了

**Comment by ChenSee** [comment]
扫码的时候固定金额码是可以的，但是手机上直接跳转是不行的需要使用输入金额码

**Comment by free3nvy** [comment]
十分感谢
