### ISSUE TITLE
用户成功付款后 余额不会增加

### ISSUE THREAD

**Issue by Loga1n** [ChenSee/ss-panel-v3-mod_Uim-alipay-wxpay#2]

**Comment by ChenSee** [comment]
@R0ac4 定时任务添加了没

**Comment by ChenSee** [comment]
```
# crontab -e
*/1 * * * * php /你的目录/xcat alipay
*/1 * * * * php /你的目录/xcat wxpay
```

**Comment by Loga1n** [comment]
@ChenSee 已经添加了定时任务了 余额还是不会增加

**Comment by ChenSee** [comment]
@R0ac4 依赖的guzzle是否是6.2呢？

**Comment by Loga1n** [comment]
@ChenSee  emmm不会看 我怀疑是支付宝cookie配置错了 请问支付宝cookie是用这行么？
![image](https://user-images.githubusercontent.com/31658241/46075181-4591de00-c1bc-11e8-8a61-b98ef096f9f9.png)

**Comment by ChenSee** [comment]
不是的应该header里面的 不是这个

**Comment by Loga1n** [comment]
@ChenSee  谢谢 是cookie的问题 建议在教程里写清楚一点。

**Comment by ChenSee** [comment]
@R0ac4 嗯嗯 有空弄一下
