### ISSUE TITLE
支付宝Cookie问题

### ISSUE THREAD

**Issue by Loga1n** [ChenSee/ss-panel-v3-mod_Uim-alipay-wxpay#3]
根据readme.md提供的网址获取的支付宝Cookie 复制到后端过几分钟网站就会发邮件提示Cookie失效 试了好多次都是这样 是不是支付宝账号被ban了呢？

**Comment by ChenSee** [comment]
@R0ac4 这几分钟是否有问题？

**Comment by Loga1n** [comment]
@ChenSee  现在试了 一分钟内没问题 过了一分钟后支付宝支付自动关闭  网站发邮件提示cookie失效

**Comment by ChenSee** [comment]
@R0ac4 支付什么的都没问题吗？

**Comment by Loga1n** [comment]
@ChenSee  今天获取了新的cookie已经不会自动关闭了 金额也会自动到账 请问这是什么问题？

**Comment by ChenSee** [comment]
是不是之前的监听没有运行起来

**Comment by Loga1n** [comment]
把服务器重启之后就解决了 可能是没有运行起来
