### ISSUE TITLE
alipay莫名其妙停止运行

### ISSUE THREAD

**Issue by bemarkt** [ChenSee/ss-panel-v3-mod_Uim-alipay-wxpay#4]
前面两者都在运行 但在 1694次后就自己关闭了 怎么 但是同时执行的nohup wxpay 却还在运行
支付宝监听第1693次运行[2018-10-19 05:02:00]
微信监听第3400次运行[2018-10-19 05:02:02]
支付宝监听第1694次运行[2018-10-19 05:02:12]
微信监听第3401次运行[2018-10-19 05:02:13]
微信监听第3402次运行[2018-10-19 05:02:24]
微信监听第3403次运行[2018-10-19 05:02:35]
微信监听第3404次运行[2018-10-19 05:02:46]
微信监听第3405次运行[2018-10-19 05:02:57]

**Comment by ChenSee** [comment]
更新依赖哦 composer update chen-see/chen-pay

**Comment by bemarkt** [comment]
昨日更新没生效😂
现在更新了

**Comment by ChenSee** [comment]
strace -p 进程id  看看。

**Comment by bemarkt** [comment]
好像蛮正常的 分析不懂 strace的内容 不过有正常connect  没有报错 logs里面也是正常

**Comment by ChenSee** [comment]
等假死了 再看看有没有问题。

**Comment by bemarkt** [comment]
ok
