### ISSUE TITLE
关于crontab按秒为单位执行

### ISSUE THREAD

**Issue by opoet** [ChenSee/ss-panel-v3-mod_Uim-alipay-wxpay#5]
能否考虑写一个脚本，在脚本里面进行模拟循环，里面设置休眠时间，同样能够达到10s循环效果，实现一条crontab控制的效果。

**Comment by ChenSee** [comment]
你可以这样
```
* * * * * for((i=1;i<=5;i++));do php /目录/xcat wxpay;sleep 10;done
* * * * * for((i=1;i<=5;i++));do php /目录/xcat alipay;sleep 10;done
```

**Comment by opoet** [comment]
但是这样还是不能设置固定时间的crontab，对宝塔面板的计划任务并不兼容，宝塔面板更易于管理

**Comment by ChenSee** [comment]
这个可以改时间 比如5改成2，10改成20，就是20秒一次。不兼容？截个图看看。加群https://t.me/chenAirport

**Comment by opoet** [comment]
我的意思是在宝塔计划任务里面必须填写定时周期并且最低为1分钟，宝塔面板定时任务并不能按照您给出的写法来设置定时任务，而若手动添加crontab,不易于宝塔面版的统一管理
