### ISSUE TITLE
支付成功后商家已收到款，但用户余额没有增加，订单也没提示支付成功

### ISSUE THREAD

**Issue by M1r0ku** [ChenSee/ss-panel-v3-mod_Uim-alipay-wxpay#8]
接入网站后，wx/zfb都可以正常支付并且商家可以收到钱，但是用户的充值页面没有确认支付成功，而是一直在订单倒计时，并且金额也没有到用户的账号。请问这是什么原因OAO？

**Comment by M1r0ku** [comment]
贴一下配置，OAO实在不知道哪一步出问题
* Cookie
![Cookie](https://ssr-1255638849.cos.ap-chengdu.myqcloud.com/SSRbackup/1cookie.png?q-sign-algorithm=sha1&q-ak=AKIDnW4SgnkU4TgiYJIpMkxzrbEhzAAzqPxX&q-sign-time=1557663341;1557664241&q-key-time=1557663341;1557664241&q-header-list=&q-url-param-list=&q-signature=63f0f3e3944ea4bf6b96aaba004ae6087b369dac)
* 定时任务
![crontab](https://ssr-1255638849.cos.ap-chengdu.myqcloud.com/SSRbackup/2crontab.png?q-sign-algorithm=sha1&q-ak=AKIDnW4SgnkU4TgiYJIpMkxzrbEhzAAzqPxX&q-sign-time=1557663320;1557664220&q-key-time=1557663320;1557664220&q-header-list=&q-url-param-list=&q-signature=b49a1e6875556e8f4819177f5c32a4b63c93c732)

* 依赖
```
[root@WellwornGlaring-VM ~]# composer show -i
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
chen-see/chen-pay       v1.2.1 免签约支付宝与微信双支付，根据COOKIE
guzzlehttp/guzzle       6.3.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises     v1.3.1 Guzzle promises library
guzzlehttp/psr7         1.5.2  PSR-7 message implementation that also provides common utility methods
psr/http-message        1.0.1  Common interface for HTTP messages
ralouphie/getallheaders 2.0.5  A polyfill for getallheaders.

```

* 时区
```
Sun May 12 20:11:23 CST 2019

```

**Comment by ghost** [comment]
跟你一样，请问你的收款码中间是支付宝的logo还是你的头像

**Comment by M1r0ku** [comment]
> 跟你一样，请问你的收款码中间是支付宝的logo还是你的头像

你问的是上传收款码的部分还是扫码充值那部分0.0
* 上传的收款码是个人收款码所以显示头像。~~但我不确定需要上传的收款码是个人码的还是商家码~~
* 扫码充值的那部分是一整个二维码，没有logo也没有头像

刚刚回头看了下使用步骤
**6. 获取微信&支付宝付款码**
* **直接到支付点加号**
* **找到收付款**      //  这里我的理解是支付宝用的是个人收款码0.0
* **点击二维码收款**
* **设置金额（如果你想多金额）**
* ...

**Comment by ghost** [comment]
> > 跟你一样，请问你的收款码中间是支付宝的logo还是你的头像
> 
> 你问的是上传收款码的部分还是扫码充值那部分0.0
> 
> * 上传的收款码是个人收款码所以显示头像，但是我不确定需要上传的收款码是个人码的还是商家码
> * 扫码充值的那部分是一整个二维码，没有logo也没有头像

第一次我上传的个人，但用我父亲的支付宝测试并没有出现支付成功的提示。第二次上传的商家，没有测试。
微信的收款码你是上传的哪一个？收付款的？

**Comment by M1r0ku** [comment]
> > > 跟你一样，请问你的收款码中间是支付宝的logo还是你的头像
> > 
> > 
> > 你问的是上传收款码的部分还是扫码充值那部分0.0
> > 
> > * 上传的收款码是个人收款码所以显示头像，但是我不确定需要上传的收款码是个人码的还是商家码
> > * 扫码充值的那部分是一整个二维码，没有logo也没有头像
> 
> 第一次我上传的个人，但用我父亲的支付宝测试并没有出现支付成功的提示。第二次上传的商家，没有测试。
> 微信的收款码你是上传的哪一个？收付款的？

对，直接就是+号下面的收付款->二维码收款

**Comment by ghost** [comment]
好像有人说要申请商户微信收款码

**Comment by ghost** [comment]
> > > > 跟你一样，请问你的收款码中间是支付宝的logo还是你的头像
> > > 
> > > 
> > > 你问的是上传收款码的部分还是扫码充值那部分0.0
> > > 
> > > * 上传的收款码是个人收款码所以显示头像，但是我不确定需要上传的收款码是个人码的还是商家码
> > > * 扫码充值的那部分是一整个二维码，没有logo也没有头像
> > 
> > 
> > 第一次我上传的个人，但用我父亲的支付宝测试并没有出现支付成功的提示。第二次上传的商家，没有测试。
> > 微信的收款码你是上传的哪一个？收付款的？
> 
> 对，直接就是+号下面的收付款->二维码收款

生成二维码时金额你设置了吗

**Comment by M1r0ku** [comment]
> > > > > 跟你一样，请问你的收款码中间是支付宝的logo还是你的头像
> > > > 
> > > > 
> > > > 你问的是上传收款码的部分还是扫码充值那部分0.0
> > > > 
> > > > * 上传的收款码是个人收款码所以显示头像，但是我不确定需要上传的收款码是个人码的还是商家码
> > > > * 扫码充值的那部分是一整个二维码，没有logo也没有头像
> > > 
> > > 
> > > 第一次我上传的个人，但用我父亲的支付宝测试并没有出现支付成功的提示。第二次上传的商家，没有测试。
> > > 微信的收款码你是上传的哪一个？收付款的？
> > 
> > 
> > 对，直接就是+号下面的收付款->二维码收款
> 
> 生成二维码时金额你设置了吗

没设置金额，设置那里不是可以不设定金额的吗

**Comment by ChenSee** [comment]
可以查看日记看看有没有运行起来。tail /你的目录/storage/logs/chenpay.log 如果没有logs目录需要新建该目录。

**Comment by M1r0ku** [comment]
> 可以查看日记看看有没有运行起来。tail /你的目录/storage/logs/chenpay.log 如果没有logs目录需要新建该目录。

你好，没有logs目录，我刚刚新建了，但是是空的，需要运行什么才可以生成日志0.0，谢谢

**Comment by ChenSee** [comment]
@fengsec 加了crond的话应该一会就会有log，如果没有可以运行 php /你的目录/xcat wxpay 这样运行看看有没有报错

**Comment by M1r0ku** [comment]
@ChenSee 你好
* 我根据你的提示运行了 `php 网站/xcat wxpay` 以及`php 网站/xcat alipay`，然后我的邮箱就收到了两个cookie失效的告警邮件。
* 最后我发现生成了日志文件，里面只有两行信息，分别是微信和支付宝监听cookie失效。

那么是否可以说明定时监听已经生效，而我只需要更新cookie就可以了？

**Comment by ChenSee** [comment]
这说明crond定时任务没有运行起来，运行起来的话应该是每10秒就会有两条记录

**Comment by M1r0ku** [comment]
@ChenSee 噢噢，那请问应该怎么做才能使其生效？

**Comment by ChenSee** [comment]
@fengsec 你的crontab里是否正确配置并启动？

**Comment by M1r0ku** [comment]
@ChenSee 原来是定时任务里的路径配置错了，现在已改正，日志文件也正常记录。明天我更新一下cookie再测试一下。谢谢大佬这么晚还在回答问题！！！

**Comment by M1r0ku** [comment]
> @fengsec 你的crontab里是否正确配置并启动？
* 经过更新cookie目前支付宝可以运行但只能持续几分钟，几分钟后就会邮件提示支付宝Cookie出现问题，生效时间内可以正常支付并且用户金额增加，服务器也有监听日志
```
支付宝监听第22次运行[2019-05-13 10:35:23]
支付宝监听暂停中[2019-05-13 10:35:33]
支付宝监听暂停中[2019-05-13 10:35:43]
支付宝监听暂停中[2019-05-13 10:36:03]
支付宝监听暂停中[2019-05-13 10:36:13]
支付宝监听暂停中[2019-05-13 10:36:23]
支付宝监听暂停中[2019-05-13 10:36:33]
支付宝监听暂停中[2019-05-13 10:36:43]
支付宝监听暂停中[2019-05-13 10:37:02]
支付宝监听暂停中[2019-05-13 10:37:12]
支付宝监听暂停中[2019-05-13 10:37:22]
支付宝监听第23次运行[2019-05-13 10:37:33]
支付宝监听暂停中[2019-05-13 10:37:44]
支付宝监听暂停中[2019-05-13 10:38:01]
支付宝监听暂停中[2019-05-13 10:38:11]
支付宝监听暂停中[2019-05-13 10:38:21]
支付宝监听暂停中[2019-05-13 10:38:31]
支付宝监听暂停中[2019-05-13 10:38:41]
支付宝监听暂停中[2019-05-13 10:39:01]
支付宝监听暂停中[2019-05-13 10:39:12]
支付宝监听暂停中[2019-05-13 10:39:22]
支付宝监听暂停中[2019-05-13 10:39:32]
支付宝监听cookie失效[2019-05-13 10:39:48]
支付宝监听cookie失效[2019-05-13 10:40:02]
支付宝监听cookie失效[2019-05-13 10:40:15]
支付宝监听cookie失效[2019-05-13 10:40:26]
支付宝监听cookie失效[2019-05-13 10:40:37]
支付宝监听cookie失效[2019-05-13 10:40:48]
支付宝监听cookie失效[2019-05-13 10:41:04]
支付宝监听cookie失效[2019-05-13 10:41:15]
支付宝监听cookie失效[2019-05-13 10:41:27]
支付宝监听cookie失效[2019-05-13 10:41:38]
支付宝监听cookie失效[2019-05-13 10:41:50]
支付宝监听cookie失效[2019-05-13 10:42:02]


```
* 另外微信cookie还是运行不了，配置完成后没有像支付宝一样发送邮件提醒Cookie正常运行

**Comment by ChenSee** [comment]
`
cd 网站目录/
composer show chen-see/chen-pay
`
看看什么版本

**Comment by M1r0ku** [comment]
> `cd 网站目录/ composer show chen-see/chen-pay`
> 看看什么版本

```
[root@WellwornGlaring-VM ssr.fengkkk.cn]# composer show chen-see/chen-pay
name     : chen-see/chen-pay
descrip. : 免签约支付宝与微信双支付，根据COOKIE
keywords : Wxpay, alipay, chenpay
versions : * v1.0.8
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/ChenSee/ChenPay.git b6442966482163fa10ed61650abb7e01172a3705
dist     : [zip] https://api.github.com/repos/ChenSee/ChenPay/zipball/b6442966482163fa10ed61650abb7e01172a3705 b6442966482163fa10ed61650abb7e01172a3705
path     : /www/wwwroot/ssr.fengkkk.cn/vendor/chen-see/chen-pay
names    : chen-see/chen-pay

autoload
psr-4
ChenPay\ => src/ChenPay

requires
guzzlehttp/guzzle ^6.3
php >=5.5

```

**Comment by ChenSee** [comment]
运行 `composer update chen-see/chen-pay`

**Comment by M1r0ku** [comment]
> 运行 `composer update chen-see/chen-pay`

昨天也尝试过update，但是跟现在一样都是提示`Killed`
```
[root@WellwornGlaring-VM ssr.fengkkk.cn]# composer update chen-see/chen-pay
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
You have new mail in /var/spool/mail/root

```

**Comment by ChenSee** [comment]
换国内镜像试试看 `composer config -g repo.packagist composer https://packagist.phpcomposer.com`

**Comment by M1r0ku** [comment]
> 换国内镜像试试看 `composer config -g repo.packagist composer https://packagist.phpcomposer.com`

查了一下被Killed应该是内存太小的问题，我找到了以下创建交换空间的方法
```
free -m
 mkdir -p /var/_swap_
 cd /var/_swap_
 #Here, 1M * 2000 ~= 2GB of swap memory
 dd if=/dev/zero of=swapfile bs=1M count=2000
 mkswap swapfile
 swapon swapfile
 echo “/var/_swap_/swapfile none swap sw 0 0” >> /etc/fstab
 #cat /proc/meminfo
 free -m
```
* 然后在~~原本有`composer.json`的文件夹下~~**网站根目录**执行`composer update`
-------------------------------------------------------------------------
~~* 然后我运行了一下`update`，提示需要创建composer.json文件~~
```
# Composer could not find a composer.json file in /var/_swap_
# To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

$ touch /var/_swap_/composer.json

```

~~* 写入json配置，` "chen-see/chen-pay": "1.2.1"`为需要更新的依赖及其版本号~~
```json
   "require": {
        "chen-see/chen-pay": "1.2.1"
    }
}

```
~~* 重新`update`~~
```
$ composer update chen-see/chen-pay

```
~~* 提示这个，不知是否成功更新~~
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing chen-see/chen-pay (v1.2.1): Loading from cache
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Writing lock file
Generating autoload files

```

**Comment by ChenSee** [comment]
@fengsec 可以了。你可以尝试运行`composer show chen-see/chen-pay`查看版本

**Comment by M1r0ku** [comment]
> composer show chen-see/chen-pay

版本是最新的v1.21了，我现在更新cookie测试一下，再次谢谢大佬！
```
name     : chen-see/chen-pay
descrip. : 免签约支付宝与微信双支付，根据COOKIE
keywords : Wxpay, alipay, chenpay
versions : * v1.2.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/ChenSee/ChenPay.git b0c2309601905d19449c89ed5598ef1e5d326112
dist     : [zip] https://api.github.com/repos/ChenSee/ChenPay/zipball/b0c2309601905d19449c89ed5598ef1e5d326112 b0c2309601905d19449c89ed5598ef1e5d326112
path     : /var/_swap_/vendor/chen-see/chen-pay
names    : chen-see/chen-pay


```

**Comment by M1r0ku** [comment]
@ChenSee 还是不行，只能运行8分钟左右就会失效

```
支付宝监听暂停中[2019-05-13 11:41:43]
支付宝监听暂停中[2019-05-13 11:41:54]
支付宝监听暂停中[2019-05-13 11:42:01]
支付宝监听暂停中[2019-05-13 11:42:11]
支付宝监听cookie失效[2019-05-13 11:42:26]
支付宝监听cookie失效[2019-05-13 11:42:37]
支付宝监听cookie失效[2019-05-13 11:42:49]
支付宝监听cookie失效[2019-05-13 11:43:04]
支付宝监听cookie失效[2019-05-13 11:43:15]
支付宝监听cookie失效[2019-05-13 11:43:27]
[root@WellwornGlaring-VM ~]#
```

**Comment by ChenSee** [comment]
@fengsec 这个是旧版本的问题，确定核心更新的位置跟运行的位置一致？

**Comment by M1r0ku** [comment]
> @fengsec 这个是旧版本的问题，确定核心更新的位置跟运行的位置一致？


~~可能是位置问题。因为刚才创建交换空间的时候进入了`/var/_swap_`，然后在里面创建了json并安装插件。现在我进入了`_swap_`并删除了里面安装的依赖。然后再在`/root`文件夹更新了一下，现在的版本是v1.2.1，我再更新cookie测试一下~~

* 还是不行，10分钟左右就自动结束了
```
支付宝监听第39次运行[2019-05-13 12:46:04]
....
支付宝监听cookie失效[2019-05-13 12:57:10]
```

* 当前版本
```
[root@WellwornGlaring-VM ~]# composer show chen-see/chen-pay
name     : chen-see/chen-pay
descrip. : 免签约支付宝与微信双支付，根据COOKIE
keywords : Wxpay, alipay, chenpay
versions : * v1.2.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/ChenSee/ChenPay.git b0c2309601905d19449c89ed5598ef1e5d326112
dist     : [zip] https://api.github.com/repos/ChenSee/ChenPay/zipball/b0c2309601905d19449c89ed5598ef1e5d326112 b0c2309601905d19449c89ed5598ef1e5d326112
path     : /root/vendor/chen-see/chen-pay
names    : chen-see/chen-pay

autoload
psr-4
ChenPay\ => src/ChenPay

requires
guzzlehttp/guzzle ^6.3
php >=5.5
You have new mail in /var/spool/mail/root

```



> @fengsec 这个是旧版本的问题，确定核心更新的位置跟运行的位置一致？

**Comment by ChenSee** [comment]
你的网站根目录在root文件夹下面？
`[root@WellwornGlaring-VM ~]#`

**Comment by M1r0ku** [comment]
> 你的网站根目录在root文件夹下面？
> `[root@WellwornGlaring-VM ~]#`

~依赖安装的目录是`/root/vendor/chen-see/chen-pay`~
依赖安装的目录是`/www/wwwroot/vendor/chen-see/chen-pay`
网站目录是`/www/wwwroot/ssr.fengkk.com/`

目前已将依赖安装在`/wwwroot/`目录下，还是会失效
```
[root@WellwornGlaring-VM wwwroot]# ls
composer.json  composer.lock  ssr.fengkkk.cn  vendor
You have new mail in /var/spool/mail/root
[root@WellwornGlaring-VM wwwroot]# composer show chen-see/chen-pay
name     : chen-see/chen-pay
descrip. : 免签约支付宝与微信双支付，根据COOKIE
keywords : Wxpay, alipay, chenpay
versions : * v1.2.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/ChenSee/ChenPay.git b0c2309601905d19449c89ed5598ef1e5d326112
dist     : [zip] https://api.github.com/repos/ChenSee/ChenPay/zipball/b0c2309601905d19449c89ed5598ef1e5d326112 b0c2309601905d19449c89ed5598ef1e5d326112
path     : /www/wwwroot/vendor/chen-see/chen-pay
names    : chen-see/chen-pay

autoload
psr-4
ChenPay\ => src/ChenPay

requires
guzzlehttp/guzzle ^6.3
php >=5.5

```

**Comment by ChenSee** [comment]
应该```cd /www/wwwroot/ssr.fengkk.com/```这里

**Comment by M1r0ku** [comment]
> 应该`cd /www/wwwroot/ssr.fengkk.com/`这里

~~刚才在网站目录下update一直被Killed...~~
`14:50`装上并更新了cookie，现在`15:13`还没有报错，应该是成功了orz

**Comment by ChenSee** [comment]
@fengsec 那应该是可以了。

**Comment by M1r0ku** [comment]
> @fengsec 那应该是可以了。

嗯嗯。另外我的微信cookie一直设置不成功可能是什么原因。
* 从`wx.qq.com`扫码登陆的后跳转到`wx2.qq.com`。我在后台配置的url是`wx.qq.com`。
* cookie配置的是`webwxinit?r=***`里的cookie，但是这个cookie是`RK=****;wxuin=******`，而不是像`README`那样以`wxuin=***开头`。
* 并且配置到后台直接警告微信cookie出现问题（旧版本和新版本都是直接出现警告）

**Comment by ChenSee** [comment]
后台需要配置为`wx2.qq.com`

**Comment by M1r0ku** [comment]
@ChenSee 都可以正常运行了，十分感谢！！！
